import type { Metadata } from "next";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NFT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (

    <html lang="en">

      <body
        style={{ backgroundColor: '#10161f' }}
        className={inter.className}
      >

        {children}

      </body>

    </html>

  );

}
